# distributed.net client makefile for Microsoft Visual C++
# see http://www.distributed.net/

# by mix-82

#PROCESSOR_ARCHITECTURE = x86
#PROCESSOR_ARCHITECTURE = AMD64
#PROCESSOR_ARCHITECTURE = OPENCL32
#PROCESSOR_ARCHITECTURE = OPENCL64

BASENAME = dnetc
OUTPUTPATH = output
COMMONPATH = common
PRIVATEPATH = ../private
RC572SRCPATH = rc5-72
OGRSRCPATH = ogr
PLATSRCPATH = plat/win

HAVE_RC5_72_CORES=1
HAVE_OGR_CORES=0
HAVE_OGR_PASS2=0
HAVE_IPV6=1

# --------------------------------------------

!ifndef PROCESSOR_ARCHITECTURE
PROCESSOR_ARCHITECTURE = x86
!endif

!message Build environment for architecture: $(PROCESSOR_ARCHITECTURE)

!if "$(PROCESSOR_ARCHITECTURE)" == "x86"
OPTS_CC_CPU = 
OPTS_M_PLAT = IX86
CHIPSRCPATH = plat/x86
ZIPSUFFIX = win32-x86
!elseif "$(PROCESSOR_ARCHITECTURE)" == "AMD64"
OPTS_CC_CPU = -D_AMD64_ -GS-
OPTS_M_PLAT = AMD64
CHIPSRCPATH = plat/AMD64
ZIPSUFFIX = win64-amd64
!elseif "$(PROCESSOR_ARCHITECTURE)" == "OPENCL32"
HAVE_OGR_CORES = 0
OPTS_CC_CPU =
OPTS_M_PLAT = IX86
CHIPSRCPATH = plat
ZIPSUFFIX = win32-x86-opencl
!elseif "$(PROCESSOR_ARCHITECTURE)" == "OPENCL64"
HAVE_OGR_CORES = 0
OPTS_CC_CPU =
OPTS_M_PLAT = AMD64
CHIPSRCPATH = plat
ZIPSUFFIX = win64-amd64-opencl
!else
!error unrecognized PROCESSOR_ARCHITECTURE found in the environment
!endif

!ifdef DEBUG
OPTS_CC_DEBUG = -MTd -Zi -DDEBUG -Od
OPTS_LINK_DEBUG = /debug /pdb:dnetc.pdb
!else
OPTS_CC_DEBUG = -MT -DNDEBUG
OPTS_LINK_DEBUG = /release
!endif

!if defined(PECOMPACT)
!if "$(OPTS_M_PLAT)" == "IX86"
EXECOMPRESSOR = "$(PECOMPACT)\pec2.exe"
EXECOMPRESSOR2 = /NoBackup /CodeIntegrityCheck:Y /StripDebug:Y /WinModuleLoader:Y
!endif
!elseif defined(UPX)
EXECOMPRESSOR = "$(UPX)\upx.exe" -9 -qq --compress-resources=0
EXECOMPRESSOR2 =
!endif

# --------------------------------------------

ZIPEXTRAS = \
	docs/readme.win32.html \
	docs/dnetc.txt \
	docs/CHANGES.txt

# --------------------------------------------

OPTS_MSVC = -nologo -D__WIN32__ \
            -W4 -GR- -GA -GF -Gy \
            -DHAVE_SNPRINTF \
            -D_M_$(OPTS_M_PLAT) $(OPTS_CC_CPU) $(OPTS_CC_DEBUG)

OPTS_LIBS = advapi32.lib user32.lib kernel32.lib gdi32.lib

OPTS_LINK = /nologo /incremental:no \
            /machine:$(OPTS_M_PLAT) $(OPTS_LINK_DEBUG)
OPTS_RC   = -d_Windows -d_M_$(OPTS_M_PLAT)

# snprintf needs to be defined for Visual Studio 2015 and earlier
!if ( [plat\win\msvcver.cmd] < 19 )
OPTS_MSVC = $(OPTS_MSVC) -Dsnprintf=_snprintf
!endif

!if ( [plat\win\msvcver.cmd] >= 19 )
OPTS_MSVC = $(OPTS_MSVC) -EHs-c- -GS- -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -wd4996
!elseif ( [plat\win\msvcver.cmd] >= 15 )
OPTS_MSVC = $(OPTS_MSVC) -EHs-c- -GS- -wd4996
!elseif ( [plat\win\msvcver.cmd] >= 14 )
OPTS_MSVC = $(OPTS_MSVC) -EHs-c- -GS- -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE
!elseif ( [plat\win\msvcver.cmd] >= 12 )
OPTS_MSVC = $(OPTS_MSVC) -GX- -GM
OPTS_LINK = $(OPTS_LINK) /warn:1 
!else
!error Failed to detect MSVC version.
!endif

# --------------------------------------------

# OpenCL support
!if "$(PROCESSOR_ARCHITECTURE)" == "OPENCL32"
OPTS_MSVC = $(OPTS_MSVC) -I"$(OPENCLDIR)include" -Iplat\opencl -Iplat\x86
OPTS_LIBS = $(OPTS_LIBS) "$(OPENCLDIR)lib\x86\OpenCL.lib"
ZIPEXTRAS = $(ZIPEXTRAS) docs\readme.opencl
!endif

!if "$(PROCESSOR_ARCHITECTURE)" == "OPENCL64"
OPTS_MSVC = $(OPTS_MSVC) -I"$(OPENCLDIR)include" -Iplat\opencl -Iplat\amd64
OPTS_LIBS = $(OPTS_LIBS) "$(OPENCLDIR)lib\x64\Opencl.lib"
ZIPEXTRAS = $(ZIPEXTRAS) docs\readme.opencl
!endif

# --------------------------------------------

all: $(BASENAME).exe $(BASENAME).com $(BASENAME).scr

# --------------------------------------------

RES_FILE = $(OUTPUTPATH)/$(BASENAME).res
RC_FILE = $(PLATSRCPATH)/w32cons.rc

# --------------------------------------------

COMMON_OBJS =                        \
        $(OUTPUTPATH)/base64.obj     \
        $(OUTPUTPATH)/bench.obj      \
        $(OUTPUTPATH)/buffbase.obj   \
        $(OUTPUTPATH)/checkpt.obj    \
        $(OUTPUTPATH)/clicdata.obj   \
        $(OUTPUTPATH)/client.obj     \
        $(OUTPUTPATH)/clievent.obj   \
        $(OUTPUTPATH)/cliident.obj   \
        $(OUTPUTPATH)/clirun.obj     \
        $(OUTPUTPATH)/clitime.obj    \
        $(OUTPUTPATH)/cmdline.obj    \
        $(OUTPUTPATH)/confmenu.obj   \
        $(OUTPUTPATH)/confopt.obj    \
        $(OUTPUTPATH)/confrwv.obj    \
        $(OUTPUTPATH)/console.obj    \
        $(OUTPUTPATH)/coremem.obj    \
        $(OUTPUTPATH)/core_r72.obj   \
        $(OUTPUTPATH)/core_ogr.obj   \
        $(OUTPUTPATH)/core_ogr_ng.obj \
        $(OUTPUTPATH)/cpucheck.obj   \
        $(OUTPUTPATH)/disphelp.obj   \
        $(OUTPUTPATH)/iniread.obj    \
        $(OUTPUTPATH)/logstuff.obj   \
        $(OUTPUTPATH)/lurk.obj       \
        $(OUTPUTPATH)/mail.obj       \
        $(OUTPUTPATH)/modereq.obj    \
        $(OUTPUTPATH)/netbase.obj    \
        $(OUTPUTPATH)/netconn.obj    \
        $(OUTPUTPATH)/pathwork.obj   \
        $(OUTPUTPATH)/pollsys.obj    \
        $(OUTPUTPATH)/probfill.obj   \
        $(OUTPUTPATH)/problem.obj    \
        $(OUTPUTPATH)/projdata.obj   \
        $(OUTPUTPATH)/probman.obj    \
        $(OUTPUTPATH)/random.obj     \
        $(OUTPUTPATH)/selcore.obj    \
        $(OUTPUTPATH)/selftest.obj   \
        $(OUTPUTPATH)/setprio.obj    \
        $(OUTPUTPATH)/stress.obj     \
        $(OUTPUTPATH)/triggers.obj   \
        $(OUTPUTPATH)/util.obj
OPTS_MSVC = $(OPTS_MSVC) -I$(COMMONPATH) -DLURK
!if exist( "$(PRIVATEPATH:/=\)\buffpriv.cpp" )
COMMON_OBJS = $(COMMON_OBJS)         \
        $(OUTPUTPATH)/buffupd.obj    \
        $(OUTPUTPATH)/buffpriv.obj   \
        $(OUTPUTPATH)/scram.obj
!else
COMMON_OBJS = $(COMMON_OBJS)         \
        $(OUTPUTPATH)/buffpub.obj
!endif

# --------------------------------------------

PLAT_OBJS =                          \
        $(OUTPUTPATH)/w32cons.obj    \
        $(OUTPUTPATH)/w32pre.obj     \
        $(OUTPUTPATH)/w32ras.obj     \
        $(OUTPUTPATH)/w32sock.obj    \
        $(OUTPUTPATH)/w32ss.obj      \
        $(OUTPUTPATH)/w32svc.obj     \
        $(OUTPUTPATH)/w32exe.obj     \
        $(OUTPUTPATH)/w32ini.obj     \
        $(OUTPUTPATH)/w32snapp.obj   \
        $(OUTPUTPATH)/w32util.obj

!if "$(PROCESSOR_ARCHITECTURE)" == "x86"
# PLAT_OBJS = $(PLAT_OBJS) $(OUTPUTPATH)/w32x86.obj
!endif
!if "$(PROCESSOR_ARCHITECTURE)" == "AMD64"
PLAT_OBJS = $(PLAT_OBJS) $(OUTPUTPATH)/strcmpi.obj
!endif

OPTS_MSVC = $(OPTS_MSVC) -I$(PLATSRCPATH) -I$(CHIPSRCPATH)

!if $(HAVE_IPV6) == 1
OPTS_MSVC = $(OPTS_MSVC) -DHAVE_IPV6
!endif

!if "$(PROCESSOR_ARCHITECTURE)" == "AMD64"
OPTS_MSVC = $(OPTS_MSVC) -I plat/x86
!endif

# --------------------------------------------

SCR_OBJS =                           \
        $(OUTPUTPATH)/w32ss.obj      \
        $(OUTPUTPATH)/w32ssb.obj     \
        $(OUTPUTPATH)/w32exe.obj     \
        $(OUTPUTPATH)/w32ini.obj     \
        $(OUTPUTPATH)/w32util.obj

!if "$(PROCESSOR_ARCHITECTURE)" == "AMD64"
SCR_OBJS = $(SCR_OBJS) $(OUTPUTPATH)/strcmpi.obj
!endif

CUI_OBJS =                           \
        $(OUTPUTPATH)/w32cuis.obj

# --------------------------------------------

!if "$(PROCESSOR_ARCHITECTURE)" == "x86"
CHIP_OBJS = $(OUTPUTPATH)/x86cpuid.obj       \
            $(OUTPUTPATH)/x86id.obj          \
            $(OUTPUTPATH)/x86rdtsc.obj       \
            $(OUTPUTPATH)/x86htcount.obj
!elseif "$(PROCESSOR_ARCHITECTURE)" == "AMD64"
CHIP_OBJS = $(OUTPUTPATH)/x86cpuid.obj       \
            $(OUTPUTPATH)/x86id.obj          \
            $(OUTPUTPATH)/x86rdtsc.obj       \
            $(OUTPUTPATH)/x86htcount.obj
!endif

# --------------------------------- RC5-72 -------------------------

!if $(HAVE_RC5_72_CORES) == 0
RC5_72_OBJS =
!elseif "$(PROCESSOR_ARCHITECTURE)" == "AMD64"
RC5_72_OBJS = \
        $(OUTPUTPATH)/r72-snjl.obj \
        $(OUTPUTPATH)/r72-kbe.obj \
        $(OUTPUTPATH)/r72-go2c.obj \
        $(OUTPUTPATH)/r72-go2d.obj \
        $(OUTPUTPATH)/r72-avx2.obj \
        $(OUTPUTPATH)/r72ansi1.obj \
        $(OUTPUTPATH)/r72ansi2.obj \
        $(OUTPUTPATH)/r72ansi4.obj
OPTS_MSVC = $(OPTS_MSVC) -DHAVE_RC5_72_CORES
!elseif "$(PROCESSOR_ARCHITECTURE)" == "x86"
RC5_72_OBJS =                        \
        $(OUTPUTPATH)/r72-ses1.obj   \
        $(OUTPUTPATH)/r72-ses2.obj   \
        $(OUTPUTPATH)/r72-dg2.obj    \
        $(OUTPUTPATH)/r72-dg3.obj    \
        $(OUTPUTPATH)/r72-dg3a.obj   \
        $(OUTPUTPATH)/r72-ss2.obj    \
        $(OUTPUTPATH)/r72-go2.obj    \
        $(OUTPUTPATH)/r72-go2a.obj   \
        $(OUTPUTPATH)/r72-go2b.obj   \
        $(OUTPUTPATH)/r72-sgp3.obj   \
        $(OUTPUTPATH)/r72-ma4.obj    \
        $(OUTPUTPATH)/r72-avx2-32.obj \
        $(OUTPUTPATH)/r72-mmx.obj
OPTS_MSVC = $(OPTS_MSVC) -DHAVE_RC5_72_CORES
!elseif "$(PROCESSOR_ARCHITECTURE)" == "OPENCL32" || "$(PROCESSOR_ARCHITECTURE)" == "OPENCL64"
RC5_72_OBJS =                      \
        $(OUTPUTPATH)/ocl_info.obj \
        $(OUTPUTPATH)/ocl_setup.obj \
        $(OUTPUTPATH)/ocl_common.obj \
        $(OUTPUTPATH)/ocl_ref.obj \
        $(OUTPUTPATH)/ocl_1pipe.obj

OPTS_MSVC = $(OPTS_MSVC) -DHAVE_RC5_72_CORES -DOPENCL -DDYN_TIMESLICE
!else
!error No RC5-72 cores for this architecture.
!endif

# --------------------------------- OGR-P2 ----------------------------

!if $(HAVE_OGR_PASS2) == 0
OGR_OBJS =
!elseif "$(PROCESSOR_ARCHITECTURE)" == "AMD64"
OGR_OBJS =                           \
        $(OUTPUTPATH)/ogr.obj        \
        $(OUTPUTPATH)/ogr_dat.obj    \
        $(OUTPUTPATH)/ogr_sup.obj
!elseif "$(PROCESSOR_ARCHITECTURE)" == "x86"
OGR_OBJS =                           \
        $(OUTPUTPATH)/ogr-a.obj      \
        $(OUTPUTPATH)/ogr-b.obj      \
        $(OUTPUTPATH)/ogr-c.obj      \
        $(OUTPUTPATH)/ogr-d.obj      \
        $(OUTPUTPATH)/ogr-e.obj      \
        $(OUTPUTPATH)/ogr-asm1-rt.obj\
        $(OUTPUTPATH)/ogr-asm2-rt-mmx.obj\
        $(OUTPUTPATH)/ogr-asm2-rt-mmx-amd.obj\
        $(OUTPUTPATH)/ogr_dat.obj    \
        $(OUTPUTPATH)/ogr_sup.obj
!else
!error No OGR-P2 cores for this architecture.
!endif

!if $(HAVE_OGR_PASS2) == 1
OPTS_MSVC = $(OPTS_MSVC) -DHAVE_OGR_PASS2
!endif

# --------------------------------- OGR-NG ----------------------------

!if $(HAVE_OGR_CORES) == 0
OGRNG_OBJS =
!elseif "$(PROCESSOR_ARCHITECTURE)" == "AMD64"
OGRNG_OBJS =                         \
        $(OUTPUTPATH)/ogr_sup.obj \
        $(OUTPUTPATH)/ogrng-64.obj   \
        $(OUTPUTPATH)/ogrng64-cj1-generic.obj    \
        $(OUTPUTPATH)/ogrng64-cj1-generic-asm.obj \
        $(OUTPUTPATH)/ogrng64-cj1-sse2.obj    \
        $(OUTPUTPATH)/ogrng64-cj1-sse2-asm.obj \
        $(OUTPUTPATH)/ogrng64-cj1-sse2-lzcnt.obj \
        $(OUTPUTPATH)/ogrng64-cj1-sse2-lzcnt-asm.obj \
        $(OUTPUTPATH)/ogrng_init.obj \
        $(OUTPUTPATH)/ogrng_dat.obj
!elseif "$(PROCESSOR_ARCHITECTURE)" == "x86"
OGRNG_OBJS =                         \
        $(OUTPUTPATH)/ogr_sup.obj \
        $(OUTPUTPATH)/ogrng-32.obj   \
        $(OUTPUTPATH)/ogrng-a.obj    \
        $(OUTPUTPATH)/ogrng-a-asm-rt.obj \
        $(OUTPUTPATH)/ogrng-b.obj    \
        $(OUTPUTPATH)/ogrng-b-asm-rt.obj \
        $(OUTPUTPATH)/ogrng-cj1-sse2.obj    \
        $(OUTPUTPATH)/ogrng-cj1-sse2-asm.obj \
        $(OUTPUTPATH)/ogrng-cj1-sse-p4.obj    \
        $(OUTPUTPATH)/ogrng-cj1-sse-p4-asm.obj \
        $(OUTPUTPATH)/ogrng-cj1-sse-k8.obj    \
        $(OUTPUTPATH)/ogrng-cj1-sse-k8-asm.obj \
        $(OUTPUTPATH)/ogrng-cj1-sse41.obj    \
        $(OUTPUTPATH)/ogrng-cj1-sse41-asm.obj \
        $(OUTPUTPATH)/ogrng-cj1-sse2-lzcnt.obj    \
        $(OUTPUTPATH)/ogrng-cj1-sse2-lzcnt-asm.obj \
        $(OUTPUTPATH)/ogrng_init.obj \
        $(OUTPUTPATH)/ogrng_dat.obj
!else
!error No OGR-NG cores for this architecture.
!endif

!if $(HAVE_OGR_CORES) == 1
# Compiler heap overflow in ogrng_dat.cpp requires -Zm option
OPTS_MSVC = $(OPTS_MSVC) -DHAVE_OGR_CORES -Zm500
!endif

# --------------------------------- OGR (common) ----------------------------

!if $(HAVE_OGR_CORES) == 1 || $(HAVE_OGR_PASS2) == 1
OPTS_MSVC = $(OPTS_MSVC) -I$(OGRSRCPATH)
!endif

# --------------------------------------------

VC_CHECK = $(OUTPUTPATH)/bltwith.vc

$(VC_CHECK):
	@-del $(OUTPUTPATH:/=\)\*.o?? $(RES_FILE:/=\)
	@echo moo > $(VC_CHECK:/=\)

# --------------------------------------------

!if "$(PROCESSOR_ARCHITECTURE)" == "AMD64"

{$(RC572SRCPATH)/ansi}.cpp{$(OUTPUTPATH)}.obj::
	cl -c -O2 $(OPTS_MSVC) -Fo$(OUTPUTPATH)\ $<

{$(RC572SRCPATH)/amd64}.asm{$(OUTPUTPATH)}.obj:
	nasm -o $(@:/=\) -f win64 -D_WINDOWS -i $(RC572SRCPATH:/=\)\amd64\ $(**:/=\)

{$(OGRSRCPATH)/amd64}.asm{$(OUTPUTPATH)}.obj:
	nasm -o $(@:/=\) -f win64 -D_WINDOWS -i $(OGRSRCPATH:/=\)\amd64\ $(**:/=\)

{$(OGRSRCPATH)/amd64}.cpp{$(OUTPUTPATH)}.obj::
	cl -c $(OPTS_MSVC) -Ox -Fo$(OUTPUTPATH)\ $<

{$(CHIPSRCPATH)}.asm{$(OUTPUTPATH)}.obj:
	nasm -o $(@:/=\) -f win64 -D_WINDOWS $(**:/=\)

{plat/x86}.cpp{$(OUTPUTPATH)}.obj::
	cl -c $(OPTS_MSVC) -Ox -Fo$(OUTPUTPATH)\ $<

!elseif "$(PROCESSOR_ARCHITECTURE)" == "x86"

{$(CHIPSRCPATH)}.asm{$(OUTPUTPATH)}.obj:
	nasm -o $(@:/=\) -f win32 -i $(CHIPSRCPATH:/=\) $(**:/=\)

{$(CHIPSRCPATH)}.cpp{$(OUTPUTPATH)}.obj::
	cl -c $(OPTS_MSVC) -Ox -Fo$(OUTPUTPATH)\ $<

{$(RC572SRCPATH)/x86}.asm{$(OUTPUTPATH)}.obj:
	nasm -o $(@:/=\) -f win32 -i $(RC572SRCPATH:/=\)\x86\ $(**:/=\)

{$(OGRSRCPATH)/x86}.asm{$(OUTPUTPATH)}.obj:
	nasm -O5 -o $(@:/=\) -f win32 -i $(OGRSRCPATH:/=\)\x86\ $(**:/=\)

{$(OGRSRCPATH)/x86}.cpp{$(OUTPUTPATH)}.obj::
	cl -c $(OPTS_MSVC) -Ox -Fo$(OUTPUTPATH)\ $<

!elseif "$(PROCESSOR_ARCHITECTURE)" == "OPENCL32"

{$(CHIPSRCPATH)/x86}.asm{$(OUTPUTPATH)}.obj:
	nasm -o $(@:/=\) -f win32 -i $(CHIPSRCPATH:/=\) $(**:/=\)

{$(CHIPSRCPATH)/x86}.cpp{$(OUTPUTPATH)}.obj::
	cl -c $(OPTS_MSVC) -Ox -Fo$(OUTPUTPATH)\ $<

{$(CHIPSRCPATH)/opencl}.cpp{$(OUTPUTPATH)}.obj::
	cl -c $(OPTS_MSVC) -Ox -Fo$(OUTPUTPATH)\ $<

{$(RC572SRCPATH)/opencl}.cpp{$(OUTPUTPATH)}.obj::
	cl -c -O2 $(OPTS_MSVC) -Fo$(OUTPUTPATH)\ $<

!elseif "$(PROCESSOR_ARCHITECTURE)" == "OPENCL64"

{$(CHIPSRCPATH)/amd64}.asm{$(OUTPUTPATH)}.obj:
	nasm -o $(@:/=\) -f win64 -D_WINDOWS $(**:/=\)

{$(CHIPSRCPATH)/amd64}.cpp{$(OUTPUTPATH)}.obj::
	cl -c $(OPTS_MSVC) -Ox -Fo$(OUTPUTPATH)\ $<

{$(CHIPSRCPATH)/opencl}.cpp{$(OUTPUTPATH)}.obj::
	cl -c $(OPTS_MSVC) -Ox -Fo$(OUTPUTPATH)\ $<

{$(RC572SRCPATH)/opencl}.cpp{$(OUTPUTPATH)}.obj::
	cl -c -O2 $(OPTS_MSVC) -Fo$(OUTPUTPATH)\ $<

!endif

{$(RC572SRCPATH)}.cpp{$(OUTPUTPATH)}.obj::
	cl -c -O2 $(OPTS_MSVC) -Fo$(OUTPUTPATH)\ $<

{$(RC572SRCPATH)/ansi}.cpp{$(OUTPUTPATH)}.obj::
	cl -c -O2 $(OPTS_MSVC) -Fo$(OUTPUTPATH)\ $<

{$(OGRSRCPATH)/ansi}.cpp{$(OUTPUTPATH)}.obj::
	cl -c -Ox $(OPTS_MSVC) -Fo$(OUTPUTPATH)\ $<

{$(PLATSRCPATH)}.cpp{$(OUTPUTPATH)}.obj::
	cl -c -Oxs $(OPTS_MSVC) -Fo$(OUTPUTPATH)\ $<

{$(PLATSRCPATH)}.c{$(OUTPUTPATH)}.obj::
	cl -c -Ox -Zl $(OPTS_MSVC) -Fo$(OUTPUTPATH)\ $<

{$(COMMONPATH)}.cpp{$(OUTPUTPATH)}.obj::
	cl -c -O2 $(OPTS_MSVC) -Fo$(OUTPUTPATH)\ $<

{$(PRIVATEPATH)}.cpp{$(OUTPUTPATH)}.obj::
	cl -c -O2 $(OPTS_MSVC) -Fo$(OUTPUTPATH)\ $<

$(RES_FILE):    $(RC_FILE)
	rc  -i $(OPTS_RC) -I$(COMMONPATH) -fo$@ $(**:/=\)

# --------------------------------------------

$(BASENAME).scr: $(VC_CHECK) $(SCR_OBJS) $(RES_FILE)
	link $(OPTS_LINK) /SUBSYSTEM:WINDOWS,4.00 /OUT:$(BASENAME).scr $(OPTS_LIBS) $(SCR_OBJS) $(RES_FILE) 
!if defined(EXECOMPRESSOR) && !defined(DEBUG)
	$(EXECOMPRESSOR) $(BASENAME).scr $(EXECOMPRESSOR2)
!endif

$(BASENAME).com: $(VC_CHECK) $(CUI_OBJS) 
	link $(OPTS_LINK) /SUBSYSTEM:CONSOLE,3.10 /OUT:$(BASENAME).com /NODEFAULTLIB $(OPTS_LIBS) $(CUI_OBJS)

$(BASENAME).exe: $(VC_CHECK) $(PLAT_OBJS) $(COMMON_OBJS) $(CHIP_OBJS) $(RC5_72_OBJS) $(OGR_OBJS) $(OGRNG_OBJS) $(RES_FILE)
	link $(OPTS_LINK) /SUBSYSTEM:WINDOWS,3.10 /OUT:$(BASENAME).exe /MAP:$(BASENAME).map $(OPTS_LIBS) $(PLAT_OBJS) $(COMMON_OBJS) $(CHIP_OBJS) $(RC5_72_OBJS) $(OGR_OBJS) $(OGRNG_OBJS) $(RES_FILE)
!if defined(EXECOMPRESSOR) && !defined(DEBUG)
	$(EXECOMPRESSOR) $(BASENAME).exe $(EXECOMPRESSOR2)
!endif

# --------------------------------------------

clean:
	-del $(OUTPUTPATH:/=\)\*.o?? $(RES_FILE:/=\)

superclean: clean
	-del $(BASENAME).map $(BASENAME).exe $(BASENAME).scr $(BASENAME).com $(BASENAME).ini buff-in.* buff-out.*

rebuild: clean all

# --------------------------------------------

makezip: $(BASENAME).exe $(BASENAME).com $(BASENAME).scr $(ZIPEXTRAS)
	-del tmpzip.zip dnetcXXX-$(ZIPSUFFIX).zip
	zip -j tmpzip.zip $**
	-rd /s tmpzipdir
	unzip -a tmpzip.zip -d tmpzipdir
	-del tmpzip.zip
	zip -jr dnetcXXX-$(ZIPSUFFIX).zip tmpzipdir
	-rd /s tmpzipdir
	FOR /F "usebackq tokens=3" %i IN (`findstr /r /c:"#define CLIENT_BUILD_FRAC[^_]" common\version.h`) DO move /y dnetcXXX-$(ZIPSUFFIX).zip dnetc%i$(BUILDNUM_APPEND)-$(ZIPSUFFIX).zip
